framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            sync: 'sync://'

            review-summary:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: review-summary
                        type: direct
                    queues:
                        parse: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1
                    multiplier: 2

        routing:
            'App\MessageBus\Message\ParseCommand': sync
            'App\MessageBus\Message\AnalyzeCommand': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
